from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field, HttpUrl

class ExcavationStatus(str, Enum):
    """Lifecycle states of a project's excavation and restoration process."""
    PENDING = "PENDING"
    DISCOVERING = "DISCOVERING"
    DISCOVERED = "DISCOVERED"
    EVALUATING = "EVALUATING"
    EVALUATED = "EVALUATED"
    UNDERSTANDING = "UNDERSTANDING"
    UNDERSTOOD = "UNDERSTOOD"
    RECONSTRUCTING = "RECONSTRUCTING"
    RECONSTRUCTED = "RECONSTRUCTED"
    RESTORATION_PLANNING = "RESTORATION_PLANNING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    RESTORING = "RESTORING"
    RESTORED = "RESTORED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    EVOLVING = "EVOLVING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"


class RepositoryProfile(BaseModel):
    """Metadata retrieved during Stage 1 — Discovery without cloning the codebase."""
    url: str = Field(..., description="The HTTPS URL of the Git repository")
    name: str = Field(..., description="The name of the repository")
    owner: str = Field(..., description="The owner (user or organization) of the repository")
    primary_language: str = Field(..., description="The main programming language used")
    languages: Dict[str, float] = Field(
        default_factory=dict, 
        description="Dictionary mapping languages to their percentage/ratio in the codebase"
    )
    stars: int = Field(default=0, ge=0, description="GitHub stars count")
    forks: int = Field(default=0, ge=0, description="GitHub forks count")
    watchers: int = Field(default=0, ge=0, description="GitHub watchers count")
    license: Optional[str] = Field(default=None, description="The license type if defined")
    contributors_count: int = Field(default=0, ge=0, description="Total active contributors")
    last_commit_at: datetime = Field(..., description="The date and time of the last commit")
    created_at: datetime = Field(..., description="The date and time of repository creation")
    readme_content: Optional[str] = Field(default=None, description="The raw contents of the README file")


class PreservationCategory(BaseModel):
    """Score card detail for a specific dimension of the Heritage Evaluation."""
    score: int = Field(..., ge=0, le=100, description="Score from 0 to 100")
    explanation: str = Field(..., description="Detailed explainable rationale for the score")


class PreservationProfile(BaseModel):
    """The multi-dimensional preservation analysis profile."""
    historical_value: PreservationCategory = Field(
        ..., description="Evolutionary impact and historical milestones"
    )
    community_value: PreservationCategory = Field(
        ..., description="Watchers, forks, stars, and ecosystem demand"
    )
    activity_sustainability: PreservationCategory = Field(
        ..., description="Commit recency and maintainer activity"
    )
    restoration_feasibility: PreservationCategory = Field(
        ..., description="Recoverability of dependencies, build files, and test suites"
    )
    educational_value: PreservationCategory = Field(
        ..., description="Usefulness as a learning resource (algorithms, design patterns)"
    )
    innovation_evolution_potential: PreservationCategory = Field(
        ..., description="Relevance of ideas and future modernization avenues"
    )


class HeritageReport(BaseModel):
    """Stage 2 — Heritage Evaluation report generated by the Heritage Evaluator agent."""
    repository_url: str = Field(..., description="Target repository URL")
    overall_score: int = Field(..., ge=0, le=100, description="Weighted average score (0 to 100)")
    profile: PreservationProfile = Field(..., description="The multidimensional preservation profile")
    worth_preserving: bool = Field(
        ..., description="True if project is recommended for restoration, False otherwise"
    )
    guiding_question_answer: str = Field(
        ..., description="Explanation of why this software deserves another chapter"
    )
    explanation: str = Field(..., description="Overall summary of the evaluation")


class AgentLog(BaseModel):
    """An record entry representing a single, auditable action performed by an agent."""
    id: str = Field(..., description="Unique UUID string for the log entry")
    project_id: str = Field(..., description="ID of the project being excavated")
    agent_name: str = Field(..., description="Name of the agent that performed the action")
    action_type: str = Field(..., description="Type of action performed (e.g. CLI_RUN, API_CALL)")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Time of the action")
    input_parameters: Dict[str, str] = Field(
        default_factory=dict, description="Parameters passed to the action"
    )
    output_result: str = Field(..., description="Result of the action (JSON or execution log)")
    explanation: str = Field(
        ..., description="Human-explainable justification for why this action was taken"
    )


class SoftwareOverview(BaseModel):
    """Stage 3 — Software Understanding report generated by the Explorer Agent."""
    entry_points: List[str] = Field(
        default_factory=list, description="Main files or directories that serve as project entry points"
    )
    dependencies: List[str] = Field(
        default_factory=list, description="Extracted library/package dependencies"
    )
    frameworks: List[str] = Field(
        default_factory=list, description="Identified application frameworks (e.g. Django, Spring, React)"
    )
    build_system: Optional[str] = Field(
        default=None, description="The detected build configuration manager (e.g. Maven, npm, CMake)"
    )
    directory_tree: Dict[str, List[str]] = Field(
        default_factory=dict, description="A mapping of folder names to their children files"
    )
    documentation_files: List[str] = Field(
        default_factory=list, description="List of markdown/text documentation files found in the source"
    )
    explanation: str = Field(..., description="Explainable description of the software structure")


class ArchitectureReport(BaseModel):
    """Stage 4 — Architecture Reconstruction report generated by the Architect Agent."""
    modules: List[str] = Field(
        default_factory=list, description="List of internal software modules/files identified"
    )
    dependencies: Dict[str, List[str]] = Field(
        default_factory=dict, description="A directed import dependency map (module -> imports)"
    )
    components: List[str] = Field(
        default_factory=list, description="High-level architectural components/layers identified (folders)"
    )
    relationships: List[str] = Field(
        default_factory=list, description="Structural coupling relationships between components"
    )
    explanation: str = Field(..., description="Explainable analysis of the system architecture")


class ExcavationState(BaseModel):
    """The complete, mutable blackboard state representing a project's excavation status."""
    project_id: str = Field(..., description="Unique identifier for the excavation project")
    repository_url: str = Field(..., description="Target Git URL of the repository")
    status: ExcavationStatus = Field(default=ExcavationStatus.PENDING, description="Current phase")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    # State data layers (gradually populated)
    profile: Optional[RepositoryProfile] = Field(
        default=None, description="Repository Profile from Discovery Stage"
    )
    heritage_report: Optional[HeritageReport] = Field(
        default=None, description="Heritage Evaluation from Stage 2"
    )
    local_path: Optional[str] = Field(
        default=None, description="The local filesystem path where the repository has been cloned"
    )
    software_overview: Optional[SoftwareOverview] = Field(
        default=None, description="Software Overview analysis from Stage 3"
    )
    architecture_report: Optional[ArchitectureReport] = Field(
        default=None, description="Architecture Reconstruction report from Stage 4"
    )
    
    audit_logs: List[AgentLog] = Field(
        default_factory=list, description="Audit logs tracking agent actions"
    )


